[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

    # Add joker to tracker or iterate modifier if already present
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
if self.ability.d_size > 0 then
    G.GAME.round_resets.discards = G.GAME.round_resets.discards + self.ability.d_size
    ease_discard(self.ability.d_size)
 end
'''
position = "after"
payload = '''
if self.ability.set == 'Joker' then
    G.E_MANAGER:add_event(Event({func = function()
        for k, v in pairs(G.GAME.purchased_jokers) do
            if v == self.ability.name then
                G.GAME.soy_mod = G.GAME.soy_mod + 1
                local soyjokes = SMODS.find_card('j_mxms_soyjoke')
                if next(soyjokes) then
                    for i = 1, #soyjokes do
                        SMODS.calculate_effect({ message = localize('k_upgrade_ex'), colour = G.C.ATTENTION },soyjokes[i])
                    end
                end
                return true
            end
        end
        G.GAME.purchased_jokers[#G.GAME.purchased_jokers + 1] = self.ability.name
    return true end }))
end
'''
match_indent = true
times = 1