[manifest]
version = "1.0.0"
dump_lua = true
priority = 1


    # Create card variable
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "perma_bonus = self.ability and self.ability.perma_bonus or 0,"
position = "after"
payload = "mxms_mult_perma_bonus = self.ability and self.ability.mxms_mult_perma_bonus or 0,"
match_indent = true
times = 1


    # Add variable to card description
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
bonus_chips = (self.ability.bonus + (self.ability.perma_bonus or 0)) > 0 and (self.ability.bonus + (self.ability.perma_bonus or 0)) or nil,
'''
position = "after"
payload = '''
mxms_bonus_mult = (self.ability.mxms_mult_perma_bonus or 0) > 0 and self.ability.mxms_mult_perma_bonus or nil,
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
elseif _c.set == 'Enhanced' then 
'''
position = "before"
payload = '''
	if specific_vars.mxms_bonus_mult then
		localize{type = 'other', key = 'maximus_card_extra_mult', nodes = desc_nodes, vars = {specific_vars.mxms_bonus_mult}}
	end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
elseif _c.set == 'Booster' then 
'''
position = "before"
payload = '''
	if specific_vars and specific_vars.mxms_bonus_mult then
		localize{type = 'other', key = 'maximus_card_extra_mult', nodes = desc_nodes, vars = {specific_vars.mxms_bonus_mult}}
	end
'''
match_indent = true