[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

[[patches]]
[patches.pattern]
target = "globals.lua"
pattern = '''
RENTAL = HEX('b18f43'),
'''
position = "after"
payload = '''
MXMS_PRIMARY = HEX('7855fc'),
MXMS_SECONDARY = HEX('901b7f'),
HOROSCOPE = HEX('e86fa5'),
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "globals.lua"
pattern = '''
Voucher = HEX("424e54"),
'''
position = "after"
payload = '''
Horoscope = HEX('d9629c'),
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "globals.lua"
pattern = '''
Edition = HEX("4ca893"),
'''
position = "after"
payload = '''
Horoscope = HEX('a64d79'),
'''
match_indent = true
times = 1