[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
if next(find_joker('Smeared Joker')) and SMODS.smeared_check(self, suit) then
    return true
end
'''
position = "after"
payload = '''
if next(SMODS.find_card('j_mxms_faded')) and faded_check(self, suit) then
    return true
end
'''
match_indent = true
times = 2

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
if next(find_joker('Smeared Joker')) and SMODS.smeared_check(self, suit) then
    return true
end
'''
position = "before"
payload = '''
if next(SMODS.find_card('j_mxms_faded')) and next(find_joker('Smeared Joker')) then
    return true
end
'''
match_indent = true
times = 2