[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

    # Change rendering code for stone cards show include rank and suit with Hammer and Chisel
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/card_draw.lua"]'''
pattern = '''
-- Don't render base dissolve shader.
    elseif not self.greyed then
        if self.children.front and (self.ability.delayed or (self.ability.effect ~= 'Stone Card' and not self.config.center.replace_base_card)) then
            self.children.front:draw_shader('dissolve')
        end
'''
position = "at"
payload = '''
-- Don't render base dissolve shader.
    elseif not self.greyed then
        if self.children.front and (self.ability.delayed or ((self.ability.effect ~= 'Stone Card' or next(SMODS.find_card('j_mxms_hammer_and_chisel')))  and not self.config.center.replace_base_card)) then
            self.children.front:draw_shader('dissolve')
        end
'''
match_indent = true
times = 1