[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

    # Change rendering code for stone cards to include rank and suit
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
--If the card has a front, draw that next
    if self.children.front and (self.ability.delayed or (self.ability.effect ~= 'Stone Card' and not self.config.center.replace_base_card)) then
'''
position = "at"
payload = '''
--If the card has a front, draw that next
    if self.children.front and (self.ability.delayed or (self.ability.effect ~= 'Stone Card' or next(SMODS.find_card('j_mxms_hammer_and_chisel')) and not self.config.center.replace_base_card)) then
'''
match_indent = true
times = 1