[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

    # Intercept skip tag from blind selection card
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "G.blind_prompt_box:get_UIE_by_ID('prompt_dynatext1').config.object.pop_delay = 0"
position = "before"
payload = '''
local _tag = e.UIBox:get_UIE_by_ID('tag_container')
G.GAME.mxms_skip_tag = _tag
'''
match_indent = true
times = 1