[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

#Blind Size Modifier (includes Hugo check)
[[patches]]
[patches.pattern]
target = 'blind.lua'
pattern = '''
self.chips = get_blind_amount(G.GAME.round_resets.ante)*self.mult*G.GAME.starting_params.ante_scaling
'''
position = "after"
payload = '''
if next(SMODS.find_card('j_mxms_hugo')) and self.mult > 1 then
    self.chips = self.chips/self.mult
end
if G.GAME.modifiers.mxms_X_blind_size then
    self.chips = self.chips*G.GAME.modifiers.mxms_X_blind_size
end
if G.GAME.modifiers.mxms_nuclear_size then
    self.chips = self.chips^G.GAME.round_resets.ante
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''
local blind_amt = get_blind_amount(G.GAME.round_resets.blind_ante)*blind_choice.config.mult*G.GAME.starting_params.ante_scaling
'''
position = "after"
payload = '''
if next(SMODS.find_card('j_mxms_hugo')) and blind_choice.config.mult > 1 then
    blind_amt = blind_amt/blind_choice.config.mult
end
if G.GAME.modifiers.mxms_X_blind_size then
    blind_amt = blind_amt*G.GAME.modifiers.mxms_X_blind_size
end
if G.GAME.modifiers.mxms_nuclear_size then
    blind_amt = blind_amt^G.GAME.round_resets.ante
end
'''
match_indent = true
times = 1


#Target Practice and Love and War Check
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''
if G.GAME.round_resets.ante == G.GAME.win_ante and G.GAME.blind:get_type() == 'Boss' then
    game_won = true
    G.GAME.won = true
end
'''
position = "at"
payload = '''
if G.GAME.round_resets.ante == G.GAME.win_ante and G.GAME.blind:get_type() == 'Boss' then
    if G.GAME.modifiers.mxms_bullseye_requirement then
        if next(SMODS.find_card('j_mxms_bullseye')) and G.GAME.modifiers.mxms_bullseye_requirement > SMODS.find_card('j_mxms_bullseye')[1].ability.extra.chips or not next(SMODS.find_card('j_mxms_bullseye')) then
            game_over = true
        end
    elseif G.GAME.modifiers.mxms_deck_size_req and #G.GAME.playing_cards ~= G.GAME.modifiers.mxms_deck_size_req then
        game_over = true
    else
        game_won = true
        G.GAME.won = true
    end
end
'''
match_indent = true
times = 1


# All Rare check
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''
if polled_rate > check_rate and polled_rate <= check_rate + v.val then
    local card = create_card(v.type, area, nil, nil, nil, nil, nil, 'sho')
'''
position = "at"
payload = '''
if polled_rate > check_rate and polled_rate <= check_rate + v.val then
    local card = nil
    if G.GAME.modifiers.mxms_all_rare and v.type == 'Joker' then
        card = create_card(v.type, area, nil, 0.99, nil, nil, nil, 'sho')
    else
        card = create_card(v.type, area, nil, nil, nil, nil, nil, 'sho')
    end
'''
match_indent = true
times = 1


# Change Matador to not trigger on every hand on Fashion Disaster
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
if self.ability.name == 'Matador' then
'''
position = "at"
payload = '''
if self.ability.name == 'Matador' and G.GAME.blind.boss then
'''
match_indent = true
times = 2


# Hand Decay and Ante Sell function
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
delay(0.4); ease_ante(1); delay(0.4); check_for_unlock({type = 'ante_up', ante = G.GAME.round_resets.ante + 1})
'''
position = "before"
payload = '''

if G.GAME.modifiers.mxms_hand_decay then
    SMODS.smart_level_up_hand(nil, G.GAME.modifiers.mxms_hand_decay, nil, -5)
end

if G.GAME.modifiers.mxms_ante_sell then
    for k, v in pairs(G.jokers.cards) do
        if not (v.ability and v.ability.eternal) then
            v:sell_card()
        end
    end

    for k, v in pairs(G.consumeables.cards) do
        if not (v.ability and v.ability.eternal) then
            v:sell_card()
        end
    end
end
'''
match_indent = true
times = 1


# Highlight Limit challenge modifier
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
{card_limit = self.GAME.starting_params.hand_size, type = 'hand'})
'''
position = "after"
payload = '''
if self.GAME.modifiers.mxms_highlight_limit then
    G.E_MANAGER:add_event(Event({
        func = function()
            SMODS.change_play_limit(self.GAME.modifiers.mxms_highlight_limit - 5)
            SMODS.change_discard_limit(self.GAME.modifiers.mxms_highlight_limit - 5)
            return true;
        end
    }))
end
'''
match_indent = true
times = 1


# Add all faces param check
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
if self.GAME.starting_params.no_faces and SMODS.Ranks[v.value].face then keep = false end
'''
position = "after"
payload = '''
if self.GAME.starting_params.mxms_all_faces and not SMODS.Ranks[v.value].face then keep = false end
'''
match_indent = true
times = 1