[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# New Colors

[[patches]]
[patches.pattern]
target = "globals.lua"
pattern = '''
RENTAL = HEX('b18f43'),
'''
position = "after"
payload = '''
MXMS_PRIMARY = HEX('7855fc'),
MXMS_SECONDARY = HEX('901b7f'),
HOROSCOPE = HEX('e86fa5'),
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "globals.lua"
pattern = '''
Voucher = HEX("424e54"),
'''
position = "after"
payload = '''
Horoscope = HEX('d9629c'),
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "globals.lua"
pattern = '''
Edition = HEX("4ca893"),
'''
position = "after"
payload = '''
Horoscope = HEX('a64d79'),
'''
match_indent = true
times = 1


# Prevent unlock check while in menu

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
if args.type == 'have_edition' then
'''
position = "at"
payload = '''
if args.type == 'have_edition' and G.STAGE == G.STAGES.RUN then
'''
match_indent = true
times = 1


# Post Handtype Scoring context

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
-- TARGET: effects before scoring starts

mult = mod_mult(G.GAME.hands[text].mult)
hand_chips = mod_chips(G.GAME.hands[text].chips)

'''
position = "after"
payload = '''
-- calculations after handtype scoring
SMODS.calculate_context({scoring_name = text, post_handtype_scoring = true})

'''
match_indent = true
times = 1