[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Patch as final end of round money adding event
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
if G.GAME.dollars >= 5 and not G.GAME.modifiers.no_interest then
    add_round_eval_row({bonus = true, name='interest', pitch = pitch, dollars = G.GAME.interest_amount*math.min(math.floor(G.GAME.dollars/5), G.GAME.interest_cap/5)})
    pitch = pitch + 0.06
    if (not G.GAME.seeded and not G.GAME.challenge) or SMODS.config.seeded_unlocks then
        if G.GAME.interest_amount*math.min(math.floor(G.GAME.dollars/5), G.GAME.interest_cap/5) == G.GAME.interest_amount*G.GAME.interest_cap/5 then 
            G.PROFILES[G.SETTINGS.profile].career_stats.c_round_interest_cap_streak = G.PROFILES[G.SETTINGS.profile].career_stats.c_round_interest_cap_streak + 1
        else
            G.PROFILES[G.SETTINGS.profile].career_stats.c_round_interest_cap_streak = 0
        end
    end
    check_for_unlock({type = 'interest_streak'})
    dollars = dollars + G.GAME.interest_amount*math.min(math.floor(G.GAME.dollars/5), G.GAME.interest_cap/5)
end
'''
position = "after"
payload = '''
if next(SMODS.find_card('j_mxms_change')) then
    local dollar_remainder = dollars % to_big(5)
    if dollar_remainder ~= to_big(0) then
        add_round_eval_row({bonus = true, name='joker', pitch = pitch, dollars = 5 - dollar_remainder, card = SMODS.find_card('j_mxms_change')[1]})
        pitch = pitch + 0.06
        dollars = dollars + (5 - dollar_remainder)
    end
end
'''
match_indent = true
times = 1