[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

    # Modify card calculate_joker function to trigger on chance
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''
function Card:calculate_joker(context)
    if self.debuff then return nil end
'''
position = "after"
payload = '''
if next(SMODS.find_card('j_mxms_schrodinger')) and self.ability.name ~= 'j_mxms_schrodinger' and pseudorandom('schro') < 1/2 then return nil end
'''
match_indent = true
times = 1