[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

    # Rewrite card scoring functionality (Includes edit for stone cards with rank and suit)
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
if self.ability.effect == 'Stone Card' or self.config.center.replace_base_card then
    return self.ability.bonus + (self.ability.perma_bonus or 0)
end
'''
position = "at"
payload = '''
if (self.ability.effect == 'Stone Card' and not next(SMODS.find_card('j_mxms_hammer_and_chisel'))) or self.config.center.replace_base_card then
    return self.ability.bonus + (self.ability.perma_bonus or 0)
elseif next(SMODS.find_card('j_mxms_secret_society')) then
    if self:get_id() == 2 then
        return 22 + self.ability.bonus + (self.ability.perma_bonus or 0)
    end
    if self:get_id() == 3 then
        return 20 + self.ability.bonus + (self.ability.perma_bonus or 0)
    end
    if self:get_id() == 4 then
        return 18 + self.ability.bonus + (self.ability.perma_bonus or 0)
    end
    if self:get_id() == 5 then
        return 16 + self.ability.bonus + (self.ability.perma_bonus or 0)
    end
    if self:get_id() == 6 then
        return 14 + self.ability.bonus + (self.ability.perma_bonus or 0)
    end
    if self:get_id() == 7 then
        return 12 + self.ability.bonus + (self.ability.perma_bonus or 0)
    end
    if self:get_id() == 8 then
        return 10 + self.ability.bonus + (self.ability.perma_bonus or 0)
    end
    if self:get_id() == 9 then
        return 8 + self.ability.bonus + (self.ability.perma_bonus or 0)
    end
    if self:get_id() == 10 or self:is_face() then
        return 6 + self.ability.bonus + (self.ability.perma_bonus or 0)
    end
    if self:get_id() == 14 then
        return 4 + self.ability.bonus + (self.ability.perma_bonus or 0)
    end
end
'''
match_indent = true
times = 1