[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Add better Unpleasant Gradient compat with Flower Pot 
# (Could be deprecated in favor of no Unpleasant Gradient animations)

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
if self.ability.name == 'Flower Pot' then
    local suits = {
        ['Hearts'] = 0,
        ['Diamonds'] = 0,
        ['Spades'] = 0,
        ['Clubs'] = 0
    }
'''
position = "at"
payload = '''
if self.ability.name == 'Flower Pot' then
    local unpleasant = SMODS.find_card('j_mxms_unpleasant_gradient')
    if next(unpleasant) then
        if unpleasant[1].ability.extra.triggered then
            return {
                message = localize{type='variable',key='a_xmult',vars={self.ability.extra}},
                Xmult_mod = self.ability.extra
            }
        end
    end
    local suits = {
        ['Hearts'] = 0,
        ['Diamonds'] = 0,
        ['Spades'] = 0,
        ['Clubs'] = 0
    }
'''
match_indent = true
times = 1