[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

    # Apply Virus search in get_flush
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = '''
  local suits = SMODS.Suit.obj_buffer
'''
position = "before"
payload = '''
  local virus = next(SMODS.find_card('j_mxms_virus'))
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = '''
if flush_count >= four_fingers then
'''
position = "at"
payload = '''
if flush_count >= (virus and flush_count == #hand and 2) or four_fingers then
'''
match_indent = true
times = 1